import { Request, Response } from "express"; import { Event, Organizer, Ticket, TicketTier } from "../models"; import { slugify } from "../utils/slug"; import { deleteGoogleEvent, insertGoogleEvent, updateGoogleEvent } from "../utils/googleCalendar";
async function syncCreate(event: any, organizerId: string) { const organizer = await Organizer.findById(organizerId); if (!organizer?.googleConnected) return; try { const googleEventId = await insertGoogleEvent(organizer, event); if (googleEventId) { event.googleEventId = googleEventId; await event.save(); } } catch (error) { console.error("Google Calendar event insert failed", error); } }
async function syncUpdate(event: any, organizerId: string, wasCancelled: boolean) { const organizer = await Organizer.findById(organizerId); if (!organizer?.googleConnected || !event.googleEventId) return; try { if (wasCancelled) { await deleteGoogleEvent(organizer, event.googleEventId); event.googleEventId = null; await event.save(); } else await updateGoogleEvent(organizer, event); } catch (error) { console.error("Google Calendar event sync failed", error); } }
export async function createEvent(req: Request, res: Response) { const body = req.body; if (!body.title || !body.startDateTime || !body.endDateTime || !body.venueType) return res.status(400).json({ error: "title, dates and venueType are required" }); let slug = slugify(body.slug || body.title); if (await Event.exists({ slug })) slug = `${slug}-${Date.now().toString(36)}`; const event = await Event.create({ ...body, slug, organizerId: req.auth!.organizerId }); await syncCreate(event, req.auth!.organizerId); return res.status(201).json(event); }
export async function updateEvent(req: Request, res: Response) { const event = await Event.findOne({ _id: req.params.id, organizerId: req.auth!.organizerId }); if (!event) return res.status(404).json({ error: "Event not found" }); const allowed = ["title", "description", "coverImageUrl", "startDateTime", "endDateTime", "venueType", "venueAddress", "onlineLink", "status", "slug"]; for (const key of allowed) if (req.body[key] !== undefined) (event as any)[key] = req.body[key]; await event.save(); await syncUpdate(event, req.auth!.organizerId, event.status === "cancelled"); return res.json(event); }
export async function deleteEvent(req: Request, res: Response) { const event = await Event.findOne({ _id: req.params.id, organizerId: req.auth!.organizerId }); if (!event) return res.status(404).json({ error: "Event not found" }); const organizer = await Organizer.findById(req.auth!.organizerId); if (organizer?.googleConnected && event.googleEventId) { try { await deleteGoogleEvent(organizer, event.googleEventId); } catch (error) { console.error("Google Calendar event delete failed", error); } } await event.deleteOne(); return res.sendStatus(204); }
export async function getPublicEvent(req: Request, res: Response) { const event = await Event.findOne({ slug: req.params.slug }); if (!event) return res.status(404).json({ error: "Event not found" }); const tiers = await TicketTier.find({ eventId: event._id, status: "active" }).lean(); return res.json({ event, tiers: tiers.map(t => ({ ...t, remaining: t.quantityCap - t.quantitySold })) }); }
export async function addTier(req: Request, res: Response) { const event = await Event.findOne({ _id: req.params.id, organizerId: req.auth!.organizerId }); if (!event) return res.status(404).json({ error: "Event not found" }); const { name, price, quantityCap, salesStart, salesEnd } = req.body; if (!name || price === undefined || !quantityCap) return res.status(400).json({ error: "name, price and quantityCap are required" }); return res.status(201).json(await TicketTier.create({ eventId: event._id, name, price, quantityCap, salesStart, salesEnd })); }
export async function listTiers(req: Request, res: Response) { const tiers = await TicketTier.find({ eventId: req.params.id }).lean(); return res.json(tiers.map(t => ({ ...t, remaining: t.quantityCap - t.quantitySold }))); }
export async function dashboard(req: Request, res: Response) { const event = await Event.findOne({ _id: req.params.id, organizerId: req.auth!.organizerId }); if (!event) return res.status(404).json({ error: "Event not found" }); const [tiers, attendees] = await Promise.all([TicketTier.find({ eventId: event._id }).lean(), Ticket.find({ eventId: event._id }).populate("tierId", "name price").lean()]); const totalRevenue = attendees.filter(t => t.status !== "refunded").reduce((sum, t: any) => sum + (t.tierId?.price || 0), 0); return res.json({ ticketsSoldPerTier: tiers.map(t => ({ tierId: t._id, name: t.name, sold: t.quantitySold, capacity: t.quantityCap })), totalRevenue, attendees }); }
